library(shiny)

# Drawing canvas
component.canvas <-
  div(
    id='canvas-group',
    tags$form(
      class='well',
      style='height:500px;',
      role='complementaly',
      conditionalPanel(
        condition='output.mode == "ready"',
        h4('Write a number in the box using a mouse'),
        div(
          class='canvas-group__component',
          HTML("<canvas id='input-canvas' width='280' height='280' style='margin:auto;'></canvas>"),
          br(),
          br(),
          actionButton('submit', 'Submit', class='btn-success', onclick='clickSubmit();'),
          HTML("<button id='clear' type='button' class='btn btn-default action-button shiny-bound-input' style='margin-left:10px;' onclick='clearCanvas()'>Clear</button>")
        ),
      ),
      conditionalPanel(
        condition='output.mode == "predicted" || output.mode == "actual"',
        div(
          style='width:80%;min-width:300px;margin:auto;',
          HTML("<img id='canvas-img' alt='Raw image from the canvas' style='margin:10px;width:280px;height:280px;' />")
        ),
        br(),
        br(),
        actionButton('reset', 'Retry', onclick='resetAll();')
      )
    )
  )

# Display actual image (28x28) used for prediction
# the data is generated from image drawn by user
component.display_predicted_image <-
  div(
    id='predicted-image-group',
    style='display:flex;',
    h4('Input image: ', style='display:inline-block;'),
    imageOutput('predicted_image', height='28px;', inline=TRUE)
  )

# Prediction-Actual count matrix table
component.count_matrix <-
  div(
    id='count_matrix-group',
    style='margin:20px;',
    plotOutput('count_matrix', width='95%')
  )

# Download all data generated by the user
component.data_download <-
  div(
    id='download-btn-group',
    class='btn-lg',
    `data-toggle`='tooltip',
    `data-placement`='bottom',
    title='Download drawn images and the labels',
    downloadButton('download_data', 'Download (.zip)')
  )

# Display prediction result component
component.result <-
  div(
    id='result-group',
    # Ready state to run prediction, and it shows current scores
    conditionalPanel(
      condition='output.mode == "ready"',
      br(),
      htmlOutput('accuracy'),
      br(),
      plotOutput('count_plot', width='95%', height='300px'),
      component.count_matrix,
    ),
    # Show result
    conditionalPanel(
      condition='output.mode == "predicted"',
      component.display_predicted_image,
      htmlOutput('prediction'),
      br(),
      h4('Is the prediction correct?'),
      actionButton('correct', 'Correct', class='btn-primary', onclick='resetAll()'),
      actionButton('incorrect', 'Incorrect', class='btn-danger', onclick='hidePrediction();'),
      br(),
      plotOutput('prob_plot', width='80%'),
    ),
    # Feedback actual result when prediction is incorrect
    conditionalPanel(
      condition='output.mode == "actual"',
      selectInput('actualValue', 'Actual number', 0:9),
      actionButton('actual', 'Send', onclick='resetAll();')
    ),
  )

component.about <-
  div(
    id='about',
    h2('About this'),
    p(paste(
      'This is a hand-written digit recognition app to classify which digit the user(you) wrote.',
      'In order to make a prediction, this uses a simple 2-layer CNN model.',
      'You can write a line in the box(canvas) appeared in the left side (this may take time for the first access to set up),',
      'and once you did and submit it, this app returns the predicted label(number).',
      'This also collects the past data in the current session, so you can see the history of scores.',
      'Additionally, clicking the download button located on the top-right side, you can download all image data and',
      'the labels associated with the each image, so you can improve the model by yourself.'
    )),
    HTML('<p>Source code: <a href="https://github.com/cds0123/handwritten-digit-recognition" target="_blank" rel="noopener noreferrer">github</a>'),
  )